#!/bin/sh
cpp -I src/include/ src/parser/expr.c -D__inline=inline -D__restrict=restrict -D__attribute__\(...\)= -D__extension__= -D__builtin_va_list=void* -D__asm__\(...\)= > .TestRun.tmp.C
./cc .TestRun.tmp.C
